name       : perl-datetime-locale
version    : 1.16
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Locale-1.16.tar.gz : dfaf4c42149c0622e80721773b8d7229d7785280503585895c9fe9f51e076cfe
license    : Artistic-2.0
component  : programming.perl
summary    : Localization support for DateTime.pm
description: |
    Localization support for DateTime.pm
builddeps  :
    - perl-datetime
    - perl-file-sharedir-install
rundeps  :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
