name       : perl-datetime-locale
version    : '1.18'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.18.tar.gz : f47e9ac0c48cf362cd676bed50ce6ddae309e71be625185f16925bf93da45732
license    : Artistic-2.0
component  : programming.perl
homepage   : https://github.com/houseabsolute/DateTime-Locale
summary    : Localization support for DateTime.pm
description: |
    Localization support for DateTime.pm
patterns   :
    - docs : [/usr/share/man]
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-tiny
    - perl-cpan-meta-check
    - perl-datetime
    - perl-devel-stacktrace
    - perl-dist-checkconflicts
    - perl-eval-closure
    - perl-exception-class
    - perl-file-copy-recursive
    - perl-file-sharedir-install
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-path-tiny
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-file-sharedir
    - perl-test-requires
    - perl-test-warnings
    - perl-try-tiny
rundeps    :
    - perl-datetime
    - perl-namespace-autoclean
    - perl-specio-exporter
    - perl-params-validationcompiler
    - perl-file-sharedir
    - perl-dist-checkconflicts
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
