name       : perl-datetime-locale
version    : 1.17
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.17.tar.gz : 0ca6598b3f89e92e3d1140e5685c69f6f795f6eed158fa482f33ce2122b35cc9
license    : Artistic-2.0
component  : programming.perl
summary    : Localization support for DateTime.pm
description: |
    Localization support for DateTime.pm
patterns:
    - docs: [/usr/share/man]
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-tiny
    - perl-cpan-meta-check
    - perl-datetime
    - perl-devel-stacktrace
    - perl-dist-checkconflicts
    - perl-eval-closure
    - perl-exception-class
    - perl-file-copy-recursive
    - perl-file-sharedir-install
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-path-tiny
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-file-sharedir
    - perl-test-requires
    - perl-test-warnings
    - perl-try-tiny
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
