name       : perl-datetime-locale
version    : '1.19'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.19.tar.gz : e25645e5820b59a4dbbcc636a75e44961ff10e4d16b2593e5bd7633b15ae2773
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://github.com/houseabsolute/DateTime-Locale
summary    : Localization support for DateTime.pm
description: |
    Localization support for DateTime.pm
patterns   :
    - docs : [/usr/share/man]
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-tiny
    - perl-cpan-meta-check
    - perl-devel-stacktrace
    - perl-dist-checkconflicts
    - perl-eval-closure
    - perl-exception-class
    - perl-file-copy-recursive
    - perl-file-sharedir-install
    - perl-ipc-system-simple
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-path-tiny
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-file-sharedir
    - perl-test-requires
    - perl-test-warnings
    - perl-try-tiny
rundeps    :
    - perl-namespace-autoclean
    - perl-specio-exporter
    - perl-params-validationcompiler
    - perl-file-sharedir
    - perl-dist-checkconflicts
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
